export const AudioQuranData = [
  {
    id: '1',
    name: 'Al-Fatihah',
    qari1: 'https://www.quranclassonline.com/audio/mishray/001.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/001.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/001.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/001.mp3',
  },
  {
    id: '2',
    name: 'Al-Baqarah',
    qari1: 'https://www.quranclassonline.com/audio/mishray/002.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/002.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/002.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/002.mp3',
  },
  {
    id: '3',
    name: 'Al-Imran',
    qari1: 'https://www.quranclassonline.com/audio/mishray/003.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/003.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/003.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/003.mp3',
  },
  {
    id: '4',
    name: 'Al-Nisa',
    qari1: 'https://www.quranclassonline.com/audio/mishray/004.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/004.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/004.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/004.mp3',
  },
  {
    id: '5',
    name: "Al-Ma'idah",
    qari1: 'https://www.quranclassonline.com/audio/mishray/005.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/005.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/005.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/005.mp3',
  },
  {
    id: '6',
    name: "Al-An'am",
    qari1: 'https://www.quranclassonline.com/audio/mishray/006.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/006.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/006.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/006.mp3',
  },
  {
    id: '7',
    name: "Al-A'raf",
    qari1:
      'https://www.quranclassonline.com/audio/mishray/007.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/007.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/007.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/007.mp3',
  },
  {
    id: '8',
    name: 'Al-Anfal',
    qari1: 'https://www.quranclassonline.com/audio/mishray/008.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/008.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/008.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/008.mp3',
  },
  {
    id: '9',
    name: 'Al-Tawbah',
    qari1: 'https://www.quranclassonline.com/audio/mishray/009.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/009.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/009.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/009.mp3',
  },
  {
    id: '10',
    name: 'Yunus',
    qari1: 'https://www.quranclassonline.com/audio/mishray/010.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/010.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/010.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/010.mp3',
  },
  {
    id: '11',
    name: 'Hud',
    qari1: 'https://www.quranclassonline.com/audio/mishray/011.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/011.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/011.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/011.mp3',
  },
  {
    id: '12',
    name: 'Yusuf',
    qari1: 'https://www.quranclassonline.com/audio/mishray/012.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/012.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/012.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/012.mp3',
  },
  {
    id: '13',
    name: "Al-Ra'd",
    qari1: 'https://www.quranclassonline.com/audio/mishray/013.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/013.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/013.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/013.mp3',
  },
  {
    id: '14',
    name: 'Ibrahim',
    qari1: 'https://www.quranclassonline.com/audio/mishray/014.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/014.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/014.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/014.mp3',
  },
  {
    id: '15',
    name: 'Al-Hijr',
    qari1: 'https://www.quranclassonline.com/audio/mishray/015.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/015.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/015.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/015.mp3',
  },
  {
    id: '16',
    name: 'Al-Nahl',
    qari1: 'https://www.quranclassonline.com/audio/mishray/016.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/016.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/016.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/016.mp3',
  },
  {
    id: '17',
    name: 'Al-Isra',
    qari1: 'https://www.quranclassonline.com/audio/mishray/017.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/017.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/017.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/017.mp3',
  },
  {
    id: '18',
    name: 'Al-Kahf',
    qari1: 'https://www.quranclassonline.com/audio/mishray/018.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/018.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/018.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/018.mp3',
  },
  {
    id: '19',
    name: 'Maryam',
    qari1: 'https://www.quranclassonline.com/audio/mishray/019.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/019.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/019.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/019.mp3',
  },
  {
    id: '20',
    name: 'Ta Ha',
    qari1: 'https://www.quranclassonline.com/audio/mishray/020.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/020.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/020.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/020.mp3',
  },
  {
    id: '21',
    name: 'Al-Anbiya',
    qari1: 'https://www.quranclassonline.com/audio/mishray/021.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/021.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/021.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/021.mp3',
  },
  {
    id: '22',
    name: 'Al-Hajj',
    qari1: 'https://www.quranclassonline.com/audio/mishray/022.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/022.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/022.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/022.mp3',
  },
  {
    id: '23',
    name: "Al-Mu'minun",
    qari1: 'https://www.quranclassonline.com/audio/mishray/023.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/023.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/023.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/023.mp3',
  },
  {
    id: '24',
    name: 'Al-Nur',
    qari1: 'https://www.quranclassonline.com/audio/mishray/024.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/024.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/024.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/024.mp3',
  },
  {
    id: '25',
    name: 'Al-Furqan',
    qari1: 'https://www.quranclassonline.com/audio/mishray/025.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/025.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/025.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/025.mp3',
  },
  {
    id: '26',
    name: "Al-Shu'ara",
    qari1: 'https://www.quranclassonline.com/audio/mishray/026.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/026.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/026.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/026.mp3',
  },
  {
    id: '27',
    name: 'Al-naml',
    qari1: 'https://www.quranclassonline.com/audio/mishray/027.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/027.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/027.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/027.mp3',
  },
  {
    id: '28',
    name: 'Al-Qasas',
    qari1: 'https://www.quranclassonline.com/audio/mishray/028.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/028.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/028.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/028.mp3',
  },
  {
    id: '29',
    name: 'Al-Ankabut',
    qari1: 'https://www.quranclassonline.com/audio/mishray/029.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/029.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/029.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/029.mp3',
  },
  {
    id: '30',
    name: 'Al-Rum',
    qari1: 'https://www.quranclassonline.com/audio/mishray/030.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/030.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/030.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/030.mp3',
  },
  {
    id: '31',
    name: 'Luqman',
    qari1: 'https://www.quranclassonline.com/audio/mishray/031.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/031.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/031.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/031.mp3',
  },
  {
    id: '32',
    name: 'Al-Sajdah',
    qari1: 'https://www.quranclassonline.com/audio/mishray/032.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/032.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/032.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/032.mp3',
  },
  {
    id: '33',
    name: 'Al-Ahzab',
    qari1: 'https://www.quranclassonline.com/audio/mishray/033.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/033.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/033.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/033.mp3',
  },
  {
    id: '34',
    name: 'Saba',
    qari1: 'https://www.quranclassonline.com/audio/mishray/034.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/034.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/034.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/034.mp3',
  },
  {
    id: '35',
    name: 'Fatir',
    qari1: 'https://www.quranclassonline.com/audio/mishray/035.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/035.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/035.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/035.mp3',
  },
  {
    id: '36',
    name: 'Ya Seen',
    qari1: 'https://www.quranclassonline.com/audio/mishray/036.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/036.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/036.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/036.mp3',
  },
  {
    id: '37',
    name: 'Al-Saffat',
    qari1: 'https://www.quranclassonline.com/audio/mishray/037.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/037.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/037.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/037.mp3',
  },
  {
    id: '38',
    name: 'Sad',
    qari1: 'https://www.quranclassonline.com/audio/mishray/038.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/038.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/038.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/038.mp3',
  },
  {
    id: '39',
    name: 'Al-Zumar',
    qari1: 'https://www.quranclassonline.com/audio/mishray/039.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/039.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/039.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/039.mp3',
  },
  {
    id: '40',
    name: "Mu'min",
    qari1: 'https://www.quranclassonline.com/audio/mishray/040.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/040.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/040.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/040.mp3',
  },
  {
    id: '41',
    name: 'Ha Meem Sajdah',
    qari1: 'https://www.quranclassonline.com/audio/mishray/041.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/041.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/041.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/041.mp3',
  },
  {
    id: '42',
    name: 'Al-Shura',
    qari1: 'https://www.quranclassonline.com/audio/mishray/042.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/042.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/042.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/042.mp3',
  },
  {
    id: '43',
    name: 'Al-Zukhruf',
    qari1: 'https://www.quranclassonline.com/audio/mishray/043.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/043.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/043.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/043.mp3',
  },
  {
    id: '44',
    name: 'Al-Dukhan',
    qari1: 'https://www.quranclassonline.com/audio/mishray/044.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/044.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/044.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/044.mp3',
  },
  {
    id: '45',
    name: 'Al-Jasiya',
    qari1: 'https://www.quranclassonline.com/audio/mishray/045.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/045.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/045.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/045.mp3',
  },
  {
    id: '46',
    name: 'Al-Ahqaf',
    qari1: 'https://www.quranclassonline.com/audio/mishray/046.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/046.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/046.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/046.mp3',
  },
  {
    id: '47',
    name: 'Muhammad',
    qari1: 'https://www.quranclassonline.com/audio/mishray/047.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/047.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/047.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/047.mp3',
  },
  {
    id: '48',
    name: 'Al-Fath',
    qari1: 'https://www.quranclassonline.com/audio/mishray/048.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/048.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/048.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/048.mp3',
  },
  {
    id: '49',
    name: 'Al-Hujurat',
    qari1: 'https://www.quranclassonline.com/audio/mishray/049.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/049.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/049.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/049.mp3',
  },
  {
    id: '50',
    name: 'Qaf',
    qari1: 'https://www.quranclassonline.com/audio/mishray/050.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/050.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/050.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/050.mp3',
  },
  {
    id: '51',
    name: 'Al-Dhariyat',
    qari1: 'https://www.quranclassonline.com/audio/mishray/051.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/051.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/051.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/051.mp3',
  },
  {
    id: '52',
    name: 'Al-Tur',
    qari1: 'https://www.quranclassonline.com/audio/mishray/052.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/052.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/052.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/052.mp3',
  },
  {
    id: '53',
    name: 'Al-najm',
    qari1: 'https://www.quranclassonline.com/audio/mishray/053.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/053.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/053.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/053.mp3',
  },
  {
    id: '54',
    name: 'Al-Qamar',
    qari1: 'https://www.quranclassonline.com/audio/mishray/054.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/054.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/054.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/054.mp3',
  },
  {
    id: '55',
    name: 'Al-Rahman',
    qari1: 'https://www.quranclassonline.com/audio/mishray/055.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/055.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/055.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/055.mp3',
  },
  {
    id: '56',
    name: "Al-Waqi'ah",
    qari1: 'https://www.quranclassonline.com/audio/mishray/056.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/056.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/056.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/056.mp3',
  },
  {
    id: '57',
    name: 'Al-Hadid',
    qari1: 'https://www.quranclassonline.com/audio/mishray/057.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/057.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/057.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/057.mp3',
  },
  {
    id: '58',
    name: 'Al-Mujadilah',
    qari1: 'https://www.quranclassonline.com/audio/mishray/058.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/058.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/058.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/058.mp3',
  },
  {
    id: '59',
    name: 'Al-Hashr',
    qari1: 'https://www.quranclassonline.com/audio/mishray/059.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/059.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/059.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/059.mp3',
  },
  {
    id: '60',
    name: 'Al-Mumtahinah',
    qari1: 'https://www.quranclassonline.com/audio/mishray/060.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/060.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/060.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/060.mp3',
  },
  {
    id: '61',
    name: 'Al-Saff',
    qari1: 'https://www.quranclassonline.com/audio/mishray/061.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/061.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/061.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/061.mp3',
  },
  {
    id: '62',
    name: "Al-Jummu'ah",
    qari1: 'https://www.quranclassonline.com/audio/mishray/062.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/062.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/062.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/062.mp3',
  },
  {
    id: '63',
    name: 'Al-Munafiqun',
    qari1: 'https://www.quranclassonline.com/audio/mishray/063.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/063.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/063.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/063.mp3',
  },
  {
    id: '64',
    name: 'Al-Taghabun',
    qari1: 'https://www.quranclassonline.com/audio/mishray/064.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/064.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/064.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/064.mp3',
  },
  {
    id: '65',
    name: 'Al-Talaq',
    qari1: 'https://www.quranclassonline.com/audio/mishray/065.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/065.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/065.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/065.mp3',
  },
  {
    id: '66',
    name: 'Al-Tahrim',
    qari1: 'https://www.quranclassonline.com/audio/mishray/066.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/066.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/066.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/066.mp3',
  },
  {
    id: '67',
    name: 'Al-Mulk',
    qari1: 'https://www.quranclassonline.com/audio/mishray/067.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/067.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/067.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/067.mp3',
  },
  {
    id: '68',
    name: 'Al-Qalam',
    qari1: 'https://www.quranclassonline.com/audio/mishray/068.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/068.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/068.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/068.mp3',
  },
  {
    id: '69',
    name: 'Al-Haqqah',
    qari1: 'https://www.quranclassonline.com/audio/mishray/069.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/069.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/069.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/069.mp3',
  },
  {
    id: '70',
    name: "Al-Ma'arij",
    qari1: 'https://www.quranclassonline.com/audio/mishray/070.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/070.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/070.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/070.mp3',
  },
  {
    id: '71',
    name: 'Nuh',
    qari1: 'https://www.quranclassonline.com/audio/mishray/071.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/071.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/071.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/071.mp3',
  },
  {
    id: '72',
    name: 'Al-Jinn',
    qari1: 'https://www.quranclassonline.com/audio/mishray/072.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/072.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/072.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/072.mp3',
  },
  {
    id: '73',
    name: 'Al-Muzammil',
    qari1: 'https://www.quranclassonline.com/audio/mishray/073.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/073.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/073.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/073.mp3',
  },
  {
    id: '74',
    name: 'Al-Muddathir',
    qari1: 'https://www.quranclassonline.com/audio/mishray/074.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/074.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/074.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/074.mp3',
  },
  {
    id: '75',
    name: 'Al-Qiyamah',
    qari1: 'https://www.quranclassonline.com/audio/mishray/075.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/075.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/075.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/075.mp3',
  },
  {
    id: '76',
    name: 'Ad-Dahr',
    qari1: 'https://www.quranclassonline.com/audio/mishray/076.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/076.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/076.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/076.mp3',
  },
  {
    id: '77',
    name: 'Al-Mursalat',
    qari1: 'https://www.quranclassonline.com/audio/mishray/077.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/077.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/077.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/077.mp3',
  },
  {
    id: '78',
    name: 'Al-Naba',
    qari1: 'https://www.quranclassonline.com/audio/mishray/078.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/078.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/078.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/078.mp3',
  },
  {
    id: '79',
    name: "Al-Nazi'at",
    qari1: 'https://www.quranclassonline.com/audio/mishray/079.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/079.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/079.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/079.mp3',
  },
  {
    id: '80',
    name: 'Abasa',
    qari1: 'https://www.quranclassonline.com/audio/mishray/080.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/080.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/080.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/080.mp3',
  },
  {
    id: '81',
    name: 'Al-Takwir',
    qari1: 'https://www.quranclassonline.com/audio/mishray/081.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/081.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/081.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/081.mp3',
  },
  {
    id: '82',
    name: 'Al-Infitar',
    qari1: 'https://www.quranclassonline.com/audio/mishray/082.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/082.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/082.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/082.mp3',
  },
  {
    id: '83',
    name: 'Al-Mutaffifin',
    qari1: 'https://www.quranclassonline.com/audio/mishray/083.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/083.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/083.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/083.mp3',
  },
  {
    id: '84',
    name: 'Al-Inshiqaq',
    qari1: 'https://www.quranclassonline.com/audio/mishray/084.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/084.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/084.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/084.mp3',
  },
  {
    id: '85',
    name: 'Al-Buruj',
    qari1: 'https://www.quranclassonline.com/audio/mishray/085.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/085.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/085.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/085.mp3',
  },
  {
    id: '86',
    name: 'Al-Tariq',
    qari1: 'https://www.quranclassonline.com/audio/mishray/086.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/086.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/086.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/086.mp3',
  },
  {
    id: '87',
    name: "Al-A'la",
    qari1: 'https://www.quranclassonline.com/audio/mishray/087.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/087.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/087.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/087.mp3',
  },
  {
    id: '88',
    name: 'Al-Ghashiyah',
    qari1: 'https://www.quranclassonline.com/audio/mishray/088.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/088.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/088.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/088.mp3',
  },
  {
    id: '89',
    name: 'Al-Fajr',
    qari1: 'https://www.quranclassonline.com/audio/mishray/089.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/089.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/089.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/089.mp3',
  },
  {
    id: '90',
    name: 'Al-Balad',
    qari1: 'https://www.quranclassonline.com/audio/mishray/090.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/090.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/090.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/090.mp3',
  },
  {
    id: '91',
    name: 'Al-Shams',
    qari1: 'https://www.quranclassonline.com/audio/mishray/091.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/091.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/091.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/091.mp3',
  },
  {
    id: '92',
    name: 'Al-Layl',
    qari1: 'https://www.quranclassonline.com/audio/mishray/092.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/092.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/092.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/092.mp3',
  },
  {
    id: '93',
    name: 'Al-Duha',
    qari1: 'https://www.quranclassonline.com/audio/mishray/093.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/093.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/093.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/093.mp3',
  },
  {
    id: '94',
    name: 'Al-Inshirah',
    qari1: 'https://www.quranclassonline.com/audio/mishray/094.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/094.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/094.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/094.mp3',
  },
  {
    id: '95',
    name: 'Al-Tin',
    qari1: 'https://www.quranclassonline.com/audio/mishray/095.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/095.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/095.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/095.mp3',
  },
  {
    id: '96',
    name: 'Al-Alaq',
    qari1: 'https://www.quranclassonline.com/audio/mishray/096.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/096.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/096.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/096.mp3',
  },
  {
    id: '97',
    name: 'Al-Qadr',
    qari1: 'https://www.quranclassonline.com/audio/mishray/097.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/097.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/097.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/097.mp3',
  },
  {
    id: '98',
    name: 'Al-Bayyinah',
    qari1: 'https://www.quranclassonline.com/audio/mishray/098.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/098.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/098.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/098.mp3',
  },
  {
    id: '99',
    name: 'Al-Zilzal',
    qari1: 'https://www.quranclassonline.com/audio/mishray/099.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/099.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/099.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/099.mp3',
  },
  {
    id: '100',
    name: 'Al-Adiyat',
    qari1: 'https://www.quranclassonline.com/audio/mishray/100.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/100.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/100.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/100.mp3',
  },
  {
    id: '101',
    name: "Al-Qari'ah",
    qari1: 'https://www.quranclassonline.com/audio/mishray/101.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/101.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/101.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/101.mp3',
  },
  {
    id: '102',
    name: 'Al-Takathur',
    qari1: 'https://www.quranclassonline.com/audio/mishray/102.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/102.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/102.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/102.mp3',
  },
  {
    id: '103',
    name: 'Al-Asr',
    qari1: 'https://www.quranclassonline.com/audio/mishray/103.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/103.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/103.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/103.mp3',
  },
  {
    id: '104',
    name: 'Al-Humazah',
    qari1: 'https://www.quranclassonline.com/audio/mishray/104.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/104.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/104.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/104.mp3',
  },
  {
    id: '105',
    name: 'Al-Fil',
    qari1: 'https://www.quranclassonline.com/audio/mishray/105.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/105.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/105.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/105.mp3',
  },
  {
    id: '106',
    name: 'Al-Quraysh',
    qari1: 'https://www.quranclassonline.com/audio/mishray/106.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/106.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/106.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/106.mp3',
  },
  {
    id: '107',
    name: "Al-Ma'un",
    qari1: 'https://www.quranclassonline.com/audio/mishray/107.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/107.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/107.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/107.mp3',
  },
  {
    id: '108',
    name: 'Al-Kawthar',
    qari1: 'https://www.quranclassonline.com/audio/mishray/108.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/108.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/108.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/108.mp3',
  },
  {
    id: '109',
    name: 'Al-Kafirun',
    qari1: 'https://www.quranclassonline.com/audio/mishray/109.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/109.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/109.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/109.mp3',
  },
  {
    id: '110',
    name: 'Al-Nasr',
    qari1: 'https://www.quranclassonline.com/audio/mishray/110.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/110.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/110.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/110.mp3',
  },
  {
    id: '111',
    name: 'Al-Lahab',
    qari1: 'https://www.quranclassonline.com/audio/mishray/111.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/111.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/111.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/111.mp3',
  },
  {
    id: '112',
    name: 'Al-Ikhlas',
    qari1: 'https://www.quranclassonline.com/audio/mishray/112.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/112.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/112.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/112.mp3',
  },
  {
    id: '113',
    name: 'Al-Falaq',
    qari1: 'https://www.quranclassonline.com/audio/mishray/113.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/113.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/113.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/113.mp3',
  },
  {
    id: '114',
    name: 'Al-Nas',
    qari1: 'https://www.quranclassonline.com/audio/mishray/114.mp3',
    qari2: 'https://www.quranclassonline.com/audio/kurd/114.mp3',
    qari3: 'https://www.quranclassonline.com/audio/sudais/114.mp3',
    qari4: 'https://www.quranclassonline.com/audio/basit/114.mp3',
  },
];
